### ISSUE TITLE
Bogus causing errors on factory girl/rbx-2.2.7 setup

### ISSUE THREAD

**Issue by adimasuhid** [psyho/bogus#60]
Hi getting errors on adding factory_girl with bogus on a rbx-2.2.7:

```
rbx-2.2.7 :003 > FactoryGirl.build :category
ArgumentError: method 'kind_of?': given 1, expected 0
    from /Users/Ace/.rvm/gems/rbx-2.2.7@cr/gems/factory_girl-4.4.0/lib/factory_girl/decorator.rb:10:in `kind_of? (method_missing)'
    from /Users/Ace/.rvm/gems/rbx-2.2.7@cr/gems/factory_girl-4.4.0/lib/factory_girl/decorator.rb:14:in `send'
    from /Users/Ace/.rvm/gems/rbx-2.2.7@cr/gems/factory_girl-4.4.0/lib/factory_girl/decorator.rb:10:in `method_missing'
    from /Users/Ace/.rvm/gems/rbx-2.2.7@cr/gems/factory_girl-4.4.0/lib/factory_girl/decorator/invocation_tracker.rb:11:in `kind_of? (method_missing)'
    from /Users/Ace/.rvm/gems/rbx-2.2.7@cr/gems/factory_girl-4.4.0/lib/factory_girl/decorator.rb:14:in `send'
    from /Users/Ace/.rvm/gems/rbx-2.2.7@cr/gems/factory_girl-4.4.0/lib/factory_girl/decorator.rb:10:in `kind_of? (method_missing)'
    from /Users/Ace/.rvm/gems/rbx-2.2.7@cr/gems/bogus-0.1.5/lib/bogus/core_ext.rb:19:in `==='
```

**Comment by psyho** [comment]
I just released a version of bogus (0.1.6) that supports RBX (it didn't before), would you care to check if the problem still persists?
